---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    eni:
      enabled: true
    kubeProxyReplacement: strict
    k8sServiceHost: rke2-server
    k8sServicePort: 6443

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  chart: argo-cd
  targetNamespace: argo-cd
  version: 4.5.7
  repo: https://argoproj.github.io/argo-helm
  valuesContent: |-
    redis-ha:
      enabled: true
    controller:
      enableStatefulSet: true
    server:
      autoscaling:
        enabled: true
        minReplicas: 2
      config:
       configManagementPlugins: |
         - name: kustomize-build-enable-helm
           generate:
             command: [ "sh", "-c" ]
             args: [ "kustomize build --enable-helm" ]
    repoServer:
      autoscaling:
        enabled: true
        minReplicas: 2

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd
    plugin:
      name: kustomize-build-enable-helm
    repoURL: https://github.com/ymmmtym/manifests
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
