---
# Depricated

# - hosts: dev
#   roles:
#     - role: ansible-role-dev
#       when: ansible_os_family != "Windows"
#   tags: dev

- hosts: dev
  tasks:
    - name: build template images by packer
      command:
        argv:
          - packer
          - build
          - packer/templates.json
          - -var-file=packer/variables.json
        creates: './packer_cache'
      failed_when: false
      tags: packer

- hosts: vyos
  gather_facts: no
  roles:
    - role: vyos
  tags: vyos
