alias l='ls'
alias ls='ls -FG'
alias ll='ls -l'
alias lla='ls -al'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'

# tmux
alias tnt="tmux new -t"
alias tat="tmux a -t"
alias tl="tmux ls"
alias tkt="tmux kill-session -t"
alias tkt-all="tmux kill-server"

# docker
alias d="docker"
alias dc="docker-compose"

