#cloud-config
# vim:syntax=yaml
user: kube
password: $6$salt$gDz3ZCV1MfDS16NbFIUfJ6xo/kvzFqw7vcuh3Gy0KlNFW7IFT0fy880o09hio.Qlan3eb66I2kFrgFA5oXxPj.
ssh_authorized_keys:
  - ${SSH_AUTHORIZED_KEY}
chpasswd: { expire: False }
ssh_pwauth: False
write_files:
  - content: ${RKE2_CONFIG}
    path: /tmp/config.yaml
    encoding: gz+b64
%{ if INSTALL_RKE2_TYPE == "server" }
  - content: ${KEEPALIVED_CONF}
    path: /tmp/keepalived.conf
    encoding: gz+b64
%{ else }%{ endif }
runcmd:
  - hostnamectl set-hostname ${HOSTNAME}
%{ if INSTALL_RKE2_TYPE == "server" }
  - apt update -y
  - apt install -y keepalived
  - mv /tmp/keepalived.conf /etc/keepalived/keepalived.conf
  - systemctl enable keepalived
  - systemctl start keepalived
%{ else }%{ endif }
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="${INSTALL_RKE2_TYPE}" sh -
  - mkdir -p /etc/rancher/rke2/
  - mv /tmp/config.yaml /etc/rancher/rke2/config.yaml
  - systemctl enable rke2-${INSTALL_RKE2_TYPE}
  - systemctl start rke2-${INSTALL_RKE2_TYPE}
%{ if INSTALL_RKE2_TYPE == "server" }
  - while [ ! -e /etc/rancher/rke2/rke2.yaml ]; do sleep 30; done
  - mkdir -p /home/kube/.kube
  - cp /etc/rancher/rke2/rke2.yaml /home/kube/.kube/config
  - chown kube:kube /home/kube/.kube/config
%{ else }%{ endif }
