#cloud-config
# vim:syntax=yaml

user: kube
password: $6$salt$gDz3ZCV1MfDS16NbFIUfJ6xo/kvzFqw7vcuh3Gy0KlNFW7IFT0fy880o09hio.Qlan3eb66I2kFrgFA5oXxPj.
ssh_authorized_keys:
  - ${SSH_AUTHORIZED_KEY}
chpasswd: { expire: False }
ssh_pwauth: False

timezone: Asia/Tokyo
locale: ja_JP.utf8

disk_setup:
  /dev/sdb:
    table_type: 'gpt'
    layout: true
    overwrite: True

fs_setup:
  - label: disk01
    filesystem: 'ext4'
    device: '/dev/sdb1'

mounts:
   - [ /dev/sdb1, /mnt/disk01, auto, "defaults,noexec" ]

package_update: true
# package_upgrade: true
packages:
  - chrony
  - nfs-common
  - open-iscsi
%{ if INSTALL_RKE2_TYPE == "server" ~}
  - keepalived
%{ endif ~}

write_files:
  - content: ${RKE2_CONFIG}
    path: /tmp/config.yaml
    encoding: gz+b64
  - content: |
      mirrors:
        docker.io:
          endpoint:
            - "https://mirror.gcr.io"
    path: /tmp/registries.yaml
%{ if INSTALL_RKE2_TYPE == "server" ~}
  - content: ${KEEPALIVED_CONF}
    path: /etc/keepalived/keepalived.conf
    encoding: gz+b64
  - content: ${MANIFESTS}
    path: /tmp/manifests.yaml
    encoding: gz+b64
%{ endif }

runcmd:
  - hostnamectl set-hostname ${HOSTNAME}
  - curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="${INSTALL_RKE2_TYPE}" sh -
  - mkdir -p /etc/rancher/rke2/
  - mv /tmp/config.yaml /etc/rancher/rke2/config.yaml
  - mv /tmp/registries.yaml /etc/rancher/rke2/registries.yaml
%{ if INSTALL_RKE2_TYPE == "server" ~}
  - mkdir -p /var/lib/rancher/rke2/server/manifests
  - mv /tmp/manifests.yaml /var/lib/rancher/rke2/server/manifests/manifests.yaml
%{ endif ~}
  - systemctl enable rke2-${INSTALL_RKE2_TYPE}
  - systemctl start rke2-${INSTALL_RKE2_TYPE}
%{ if INSTALL_RKE2_TYPE == "server" ~}
  - while [ ! -e /etc/rancher/rke2/rke2.yaml ]; do sleep 30; done
  - mkdir -p /home/kube/.kube
  - cp /etc/rancher/rke2/rke2.yaml /home/kube/.kube/config
  - chown kube:kube /home/kube/.kube/config
%{ endif ~}
