#cloud-config
# vim:syntax=yaml
user: kube
password: $6$salt$gDz3ZCV1MfDS16NbFIUfJ6xo/kvzFqw7vcuh3Gy0KlNFW7IFT0fy880o09hio.Qlan3eb66I2kFrgFA5oXxPj.
ssh_authorized_keys:
  - ${SSH_AUTHORIZED_KEY}
chpasswd: { expire: False }
ssh_pwauth: False
write_files:
  - content: ${HAPROXY_CFG}
    path: /tmp/haproxy.cfg
    encoding: gz+b64
  - content: ${KEEPALIVED_CONF}
    path: /tmp/keepalived.conf
    encoding: gz+b64
bootcmd:
  - /usr/sbin/sysctl -q -w net.ipv4.ip_forward=1
runcmd:
  - hostnamectl set-hostname ${HOSTNAME}
  - apt update -y
  - apt -y install haproxy keepalived
  - systemctl enable haproxy keepalived
  - mv /tmp/haproxy.cfg /etc/haproxy/haproxy.cfg
  - mv /tmp/keepalived.conf /etc/keepalived/keepalived.conf
  - systemctl restart haproxy keepalived
