---
# defaults file for roles/vyos
vlans:
  - id: 1
    type: 'outbound'
    eth: 'eth0'
    cidr: '192.168.0.0/24'
  - id: 100
    type: 'public'
    eth: 'eth1'
    cidr: '192.168.100.0/24'
  - id: 101
    type: 'private'
    eth: 'eth2'
    cidr: '192.168.101.0/24'
dhcp:
  range: '{{ range(4,128) }}'
  static_mapping: '{{ range(4,16) }}'
ntp:
  servers:
    - ntp.nict.jp
