---
# defaults file for roles/vyos
dhcp_range: '{{ range(4,128) }}'
dhcp_static_mapping: '{{ range(4,16) }}'
vlans:
  - id: 1
    type: 'outbound'
    eth: 'eth0'
    cidr: '192.168.0.0/24'
  - id: 100
    type: 'public'
    eth: 'eth1'
    cidr: '192.168.100.0/24'
  - id: 101
    type: 'private'
    eth: 'eth2'
    cidr: '192.168.101.0/24'
