all:
  hosts:
    esxi:
      vars:
        ansible_host: 192.168.0.2
  children:
    dev:
      hosts: localhost
      vars:
        ansible_connection: local
    vyos:
      hosts:
        vyos01:
        vyos02:
    kubernetes:
      children:
        k8s-master:
          hosts:
            k8s-master01:
            k8s-master02:
        k8s-worker:
          hosts:
            k8s-worker01:
            k8s-worker02:
            k8s-worker03:
