---
name: Packer
on:
  pull_request:
    branches: [ main ]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    defaults:
      run:
        working-directory: ./packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: packer/templates.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/templates.json

      # build artifact
      # - name: Build Artifact
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: build
      #     arguments: "-color=false -on-error=abort"
      #     target: packer/templates.json
      #   env:
      #     PACKER_LOG: 1
