---
name: VyOS Rolling Update Notify
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  rolling-update-notify:
    runs-on: ubuntu-latest
    name: VyOS Rolling Update Notify
    defaults:
      run:
        working-directory: ./packer
    env:
      JSON: variables.json
      ISO_URL_KEY: vyos_rolling_iso_url
      ISO_CHECKSUM_KEY: vyos_rolling_iso_checksum
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: sudo apt install -y jq
      - name: Set sha256 of vyos-rolling-latest from server
        id: latest_version
        run: |
          ISO_URL=$(jq -r '."'$ISO_URL_KEY'"' $JSON)
          echo "::set-output name=checksum::$(curl -s ${ISO_URL}.sha256 | awk '{print $1}')"
          echo "::set-output name=iso_file_name::$(curl -s ${ISO_URL}.sha256 | awk '{print $2}')"
      - name: Override template.json
        run: |
          CHECKSUM=${{ steps.latest_version.outputs.checksum }}
          jq '."'$ISO_CHECKSUM_KEY'"|="'$CHECKSUM'"' $JSON > /var/tmp/$JSON
          cp /var/tmp/$JSON $JSON
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "[VyOS Rolling Update Notify] ${{ steps.latest_version.outputs.iso_file_name }}"
          commit-message: Rolling Update Image to ${{ steps.latest_version.outputs.iso_file_name }}
          branch: rolling-update/${{ steps.latest_version.outputs.iso_file_name }}
          delete-branch: true
